DROP TABLE IF EXISTS NOTIFICATIONS
GO

CREATE TABLE NOTIFICATIONS
(
	ID				INT									NOT NULL,
	USER_ID			INT									NOT NULL,
	ORDER_ID		INT									NOT NULL,
	MESSAGE			VARCHAR(512)						NOT NULL,
	REGISTER_DATE	DATE								NOT NULL,
	SEEN_BY_USER	BIT									NOT NULL,			
	CONSTRAINT PK_NOTIFICATIONS_ID  PRIMARY KEY (ID)

)
GO

EXEC SP_ADD_NEW_COUNTER 'NOTIFICATIONS', 'NOTIFICATIONS' ,'ID'
GO

