CREATE OR ALTER VIEW VI_COMPANIES
AS
	SELECT 
		COMPANY.ID				AS ID,
		COMPANY.NAME			AS NAME,
		COMPANY.EGFN			AS EGFN,
		COMPANY.PHONE_NUMBER	AS PHONE_NUMBER,
		COMPANY.EMAIL			AS EMAIL,
		CITY.NAME				AS CITY_NAME,
		CITY.STATE				AS STATE,
		CITY.POST_CODE			AS POST_CODE
	FROM COMPANIES 
		AS COMPANY WITH(NOLOCK) 
	INNER JOIN CITIES 
		AS CITY WITH(NOLOCK)
	ON COMPANY.CITY_ID = CITY.ID
GO