IF EXISTS 
(
	SELECT * FROM SYS.tables WITH(NOLOCK)
	WHERE object_id = OBJECT_ID(N'dbo.COUNTERS', N'U')
) 
BEGIN
	DROP TABLE dbo.COUNTERS
END


CREATE TABLE COUNTERS
(
	COUNTER_NAME				NVARCHAR(128) NOT NULL,
	TABLE_NAME					NVARCHAR(128) NOT NULL,
	PRIMARY_KEY_COLUMN_NAME		NVARCHAR(128) NOT NULL,
	START_INDEX					INT			  NOT NULL,
	CURRENT_INDEX_POSITION		INT			  NOT NULL,
	INDEX_STEP					INT			  NOT NULL,
	[DESCRIPTION]				NVARCHAR(504) NOT NULL,
)
GO

CREATE CLUSTERED INDEX IX_COUNTERS_TABLE_NAME_PRIMARY_KEY_COLUMN_NAME
ON COUNTERS
(
	TABLE_NAME,
	PRIMARY_KEY_COLUMN_NAME
)
GO

CREATE OR ALTER PROCEDURE SP_ADD_NEW_COUNTER
	@COUNTER_NAME				NVARCHAR(128),
	@TABLE_NAME					NVARCHAR(128),
	@COLUMN_NAME				NVARCHAR(128),
	@START_INDEX				INT	= 1,
	@CURRENT_INDEX_POSITION		INT	= 1,
	@INDEX_STEP					INT = 1	,		
	@DESCRIPTION				NVARCHAR(504) = N''
AS
BEGIN

IF EXISTS
(
	SELECT * FROM COUNTERS
	WHERE TABLE_NAME = @TABLE_NAME
)	
BEGIN
	PRINT 'COUNTER ALREADY EXISTS!'
	RETURN
END

	INSERT INTO COUNTERS
	(
		COUNTER_NAME			,		
		TABLE_NAME				,
		PRIMARY_KEY_COLUMN_NAME	,
		START_INDEX				,
		CURRENT_INDEX_POSITION	,
		INDEX_STEP				,
		[DESCRIPTION]			
	)
	VALUES(@COUNTER_NAME, @TABLE_NAME, @COLUMN_NAME, @START_INDEX, @CURRENT_INDEX_POSITION, @INDEX_STEP,@DESCRIPTION)

	PRINT 'COUNTER SUCCESSFULLY ADDED!'
END
GO

