DROP TABLE IF EXISTS CLIENTS
GO 

CREATE TABLE CLIENTS
(
	ID				INT				NOT NULL,
	UPDATE_COUNTER	INT				NOT NULL,
	NAME			NVARCHAR(128)	NOT NULL,
	UCN				NVARCHAR(16)	NOT NULL,
	COMPANY_ID		INT				NOT NULL,
	PHONE_NUMBER	NVARCHAR(16)	NOT NULL,
	CONSTRAINT PK_CLIENTS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_CLIENTS_COMPANY_ID FOREIGN KEY(COMPANY_ID)
	REFERENCES COMPANIES(ID)
)
GO

CREATE UNIQUE INDEX UX_CLIENTS_UCN
ON CLIENTS(UCN)
GO