DROP TABLE IF EXISTS EMPLOYEES
GO

CREATE TABLE EMPLOYEES
(
	ID					INT				NOT NULL ,
	UPDATE_COUNTER		INT				NOT NULL ,
	FIRST_NAME			NVARCHAR(64)	NOT NULL ,
	MIDDLE_NAME			NVARCHAR(64)	NOT NULL ,
	LAST_NAME			NVARCHAR(64)	NOT NULL ,
	UCN					NVARCHAR(32)	NOT NULL ,
	DATE_OF_BIRTH		DATE			NOT NULL ,
	GENDER				TINYINT			NOT NULL , 
	TELEPHONE_NUMBER	NVARCHAR(16)    NOT NULL ,
	EMAIL				NVARCHAR(64)	NOT NULL ,
	[USER_ID]			INT				NOT NULL ,			
	CITY_ID				INT				NOT NULL ,
	COMPANY_ID			INT				NOT NULL ,

	CONSTRAINT PK_EMPLOYEES_ID PRIMARY KEY(ID),
	CONSTRAINT FK_EMPLOYEES_CITIES_ID FOREIGN KEY(CITY_ID)
	REFERENCES CITIES(ID),
	CONSTRAINT FK_EMPLOYEES_USERS_ID FOREIGN KEY([USER_ID])
	REFERENCES USERS(ID),
	CONSTRAINT FK__EMPLOYEES_COMPANIES_ID FOREIGN KEY(COMPANY_ID)
	REFERENCES COMPANIES(ID)
)
GO

CREATE UNIQUE INDEX UX_EMPLOYEES_UCN ON EMPLOYEES
(
	UCN
)
GO

CREATE UNIQUE INDEX UX_EMPLOYEES_TELEPHONE_NUMBER ON EMPLOYEES
(
	TELEPHONE_NUMBER
)
GO

CREATE UNIQUE INDEX UX_EMPLOYEES_TELEPHONE_EMAIL ON EMPLOYEES
(
	EMAIL
)
GO

EXEC SP_ADD_NEW_COUNTER N'EMPLOYEES', N'EMPLOYEES', N'ID'
GO



