DROP TABLE IF EXISTS OFFICES
GO

CREATE TABLE OFFICES
(
	ID					INT				NOT NULL,
	UPDATE_COUNTER		INT				NOT NULL,
	NAME				VARCHAR(128)	NOT NULL,
	COMPANY_ID			INT				NOT NULL,
	CITY_ID				INT				NOT NULL,
	[ADDRESS]			NVARCHAR(256)	NOT NULL,
	DATE_ESTABLISHED	DATE			NOT NULL,
	CONSTRAINT PK_OFFICES_ID PRIMARY KEY(ID),
	CONSTRAINT FK_OFFICES_COMPANY_ID_COMPANIES_ID
	FOREIGN KEY(COMPANY_ID)
	REFERENCES COMPANIES(ID)
)
GO

CREATE UNIQUE INDEX UX_OFFICES_CITY_ID_ADDRESS
ON OFFICES
(
	CITY_ID,
	[ADDRESS]
)
GO

EXEC SP_ADD_NEW_COUNTER N'OFFICES', N'OFFICES', N'ID'