DROP TABLE IF EXISTS ORDER_TYPES
GO

CREATE TABLE ORDER_TYPES
(
	ID		INT			NOT NULL,
	NAME	VARCHAR(32) NOT NULL,
	PRICE	FLOAT		NOT NULL,
	CONSTRAINT PK_OREDER_TYPES_ID PRIMARY KEY(ID),
	CONSTRAINT UC_OREDER_TYPES_NAME UNIQUE (NAME)
)
GO

DROP TABLE IF EXISTS OREDERS
GO

CREATE TABLE OREDERS
(
	ID					INT			NOT NULL,
	UPDATE_COUNTER		INT			NOT NULL,
	OFFICE_ID			INT			NOT NULL,
	COMPANY_ID			INT			NOT NULL,
	ORDER_TYPE_ID		INT			NOT NULL,
	EMPLOYEE_ID			INT			NOT NULL,
	CLIENT_ID			INT			NOT NULL,
	DATE_REGISTERED		DATETIME	NOT NULL,
	[STATUS]			TINYINT		NOT NULL,
	CONSTRAINT PK_OREDERS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_OREDERS_OFFICES_ID FOREIGN KEY(OFFICE_ID) 
	REFERENCES OFFICES(ID),
	CONSTRAINT FK_ORDERS_COMPANIES_IDFOREIGN FOREIGN KEY(COMPANY_ID)
	REFERENCES COMPANIES(ID)
)
GO

EXEC SP_ADD_NEW_COUNTER 'ORDERS', 'ORDERS', 'ID'

