DROP TABLE IF EXISTS ORDER_TYPES
GO

CREATE TABLE OREDER_TYPES
(
	ID		INT			NOT NULL,
	NAME	VARCHAR(32) NOT NULL,
	PRICE	FLOAT		NOT NULL,
	CONSTRAINT PK_OREDER_TYPES_ID PRIMARY KEY(ID)
)
GO

DROP TABLE IF EXISTS OREDERS
GO

CREATE TABLE OREDERS
(
	ID				INT NOT NULL,
	UPDATE_COUNTER  INT	NOT NULL,
	COMPANY_ID		INT NOT NULL,
	OFFICE_ID		INT NOT NULL,
	ORDER_TYPE		INT NOT NULL,
	CLIENT_ID		INT NOT NULL,
)

