CREATE OR ALTER PROCEDURE dbo.SP_REJECT_ORDER
			@ORDER_ID AS INT,
			@USER_ID  AS INT
AS
BEGIN

	DECLARE @CURRENT_ORDER_STATUS AS INT = (SELECT STATUS FROM ORDERS WITH(NOLOCK) WHERE ID = @ORDER_ID)
	DECLARE @ORDER_STATUST_REJECTED AS INT = 2/*REJECTED*/

	IF(@CURRENT_ORDER_STATUS = @ORDER_STATUST_REJECTED)
		RETURN

	UPDATE ORDERS
	SET STATUS = @ORDER_STATUST_REJECTED
	WHERE ID = @ORDER_ID

	DECLARE @NOTIFICATION_ID AS INT
	EXEC SP_GENERATE_NEXT_UNIQUE_ID 'NOTIFICATIONS', @NOTIFICATION_ID OUTPUT

	INSERT INTO NOTIFICATIONS
	SELECT
		@NOTIFICATION_ID														AS [ID],
		@USER_ID																AS [USER_ID],
		@ORDER_ID																AS [ORDER_ID],
		CONCAT('Order with ID - ',@ORDER_ID, ' was rejected')					AS [MESSAGE],
		GETDATE()																AS [REGISTER_DATE],
		0																		AS [SEEN_BY_USER]
		
END
GO