CREATE OR ALTER PROCEDURE SP_REINIT_COUNTER
(
	@COUNTER_NAME			AS VARCHAR,
	@CURRENT_INDEX_POSITION AS INT
)
AS
BEGIN
	 UPDATE COUNTERS
	 SET CURRENT_INDEX_POSITION = @CURRENT_INDEX_POSITION
	 WHERE COUNTER_NAME = @COUNTER_NAME	
END
GO