CREATE OR ALTER VIEW VI_COMPANY_STATISTICS
AS
	SELECT
		COMPANY.ID						AS COMPANY_ID,
		COMPANY.NAME					AS COMPANY_NAME,
		COUNT(CLIENT.ID)				AS TOTAL_CLIENTS,
		COUNT(EMPLOYEE.ID)			    AS TOTAL_EMPLOYEES,
		SUM(ORDER_PRICE)				AS TOTAL_AMOUNT
		FROM VI_ORDERS WITH(NOLOCK)
	INNER JOIN COMPANIES AS COMPANY WITH(NOLOCK)
		ON VI_ORDERS.COMPANY_NAME = COMPANY.NAME
	INNER JOIN CLIENTS AS CLIENT WITH(NOLOCK)
		ON CLIENT.ID = VI_ORDERS.CLIENT_ID
	INNER JOIN EMPLOYEES AS EMPLOYEE
		ON EMPLOYEE.ID = VI_ORDERS.EMPLOYEE_ID
	WHERE VI_ORDERS.ORDER_STATUS_ID = 0
	GROUP BY COMPANY.ID,COMPANY.NAME

GO