CREATE OR ALTER VIEW VI_EMPLOYEE_STATISTICS
AS
SELECT 
	EMPLOYEES.ID		AS EMPLOYEE_ID, 
	EMPLOYEES.FIRST_NAME, 
	EMPLOYEES.LAST_NAME, 
	EMPLOYEES.UCN		AS EMPLOYEE_UCN,
	COMPANY.ID, 
	COMPANY.NAME		AS COMPANY_NAME,
	COUNT([ORDER].ID)	AS TOTAL_ORDERS
FROM EMPLOYEES WITH(NOLOCK)
INNER JOIN ORDERS AS [ORDER] WITH(NOLOCK)
	ON [ORDER].EMPLOYEE_ID = EMPLOYEES.ID
INNER JOIN COMPANIES AS COMPANY WITH(NOLOCK)
	ON EMPLOYEES.COMPANY_ID = COMPANY.ID
GROUP BY EMPLOYEES.ID, EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, COMPANY.ID, COMPANY.NAME, EMPLOYEES.UCN
GO

CREATE OR ALTER VIEW VI_EMPLOYEE_STATISTICS
AS
SELECT 
	EMPLOYEES.ID		AS EMPLOYEE_ID, 
	EMPLOYEES.FIRST_NAME, 
	EMPLOYEES.LAST_NAME, 
	EMPLOYEES.UCN		AS EMPLOYEE_UCN,
	COMPANY.ID, 
	COMPANY.NAME		AS COMPANY_NAME,
	COUNT([ORDER].ID)	AS TOTAL_ORDERS
FROM EMPLOYEES WITH(NOLOCK)
INNER JOIN ORDERS AS [ORDER] WITH(NOLOCK)
	ON [ORDER].EMPLOYEE_ID = EMPLOYEES.ID
INNER JOIN COMPANIES AS COMPANY WITH(NOLOCK)
	ON EMPLOYEES.COMPANY_ID = COMPANY.ID
GROUP BY EMPLOYEES.ID, EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, COMPANY.ID, COMPANY.NAME, EMPLOYEES.UCN
GO